default_base_path: /opt/bulletin
default_chain_spec_dl_url:
  https://raw.githubusercontent.com/paritytech/polkadot-bulletin-chain/main/chainspecs/{{
  default_network | replace('bulletin-', '') }}-chainspec.json
default_chains_name: bulletin-polkadot
default_client_version: polkadot-stable2603-4
default_database: paritydb
default_database_path: "{{ default_base_path }}/chains"
default_download_base_url: https://github.com/paritytech/polkadot-sdk/releases/download/
default_download_url: "{{ default_download_base_url }}{{ default_client_version }}/polkadot-omni-node"
default_omni_node_binaries:
  - polkadot-omni-node
  - polkadot-prepare-worker
  - polkadot-execute-worker
default_group: "{{ service_users['bulletin'] }}"
default_in_peers: 32
default_log_level: info
default_network: bulletin-polkadot
default_node_type: collator
default_out_peers: 16
default_p2p_port: 30533
default_p2p_port_ws: 30534
default_p2p_port_wss: 30535
default_prom_port: 7400
default_rpc_port: 9400
default_secure_rpc_port: 42400
default_service: bulletin
default_storage: "{{ default_base_path }}/chains"
default_telemetry_url: wss://telemetry-backend.w3f.community/submit/ 1
default_user: "{{ service_users['bulletin'] }}"
zabbix_ext_port: 10500
