#!/bin/bash

log() {
	echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
}

usage() {
	cat <<EOF
Usage: $0 <account_name> <ssh_key_path>

Arguments:
<account_name> The username for the remote host.
<ssh_key_path> The path to the SSH private key to use for authentication.

Example: $0 root ~/.ssh/ansible_ssh_key

Reqs: apt install python3 python3-venv python3-pip
This script sets up a development environment setting up proxmox using ansible.
EOF
}

account_name="$1"
ssh_key_path="$2"
ssh_folder_path="$HOME/.ssh/unlabore"

if [[ ! -f "$ssh_key_path" ]]; then
	log "The SSH key file does not exist."
	usage
	exit 1
fi

mkdir -p "$ssh_folder_path"
cp "$ssh_key_path" "$ssh_folder_path/ansible_ssh_key"

python3 -m venv venv
source ./venv/bin/activate
pip install -r ./requirements.txt
pip install -r ./requirements-dev.txt

ansible-galaxy install -r requirements.yaml

. ./venv/bin/activate

pip install git+https://github.com/hitchhooker/AISTool
export SSH_CONFIG_TARGET=~/.ssh/unlabore/config
export SSH_CONFIG_USER="$account_name"
export SSH_CONFIG_IDENTITY=~/.ssh/unlabore/ansible_ssh_key
if ! grep -qxF "Include ~/.ssh/unlabore/config" ~/.ssh/config; then echo "Include ~/.ssh/unlabore/config" >>~/.ssh/config; fi
inv sshconfig

read -p "Do you want to set up the SSH Agent service for forwarding? (y/n): " setup_ssh_agent

if [[ $setup_ssh_agent =~ ^[Yy]$ ]]; then
	log "Setting up SSH Agent service for forwarding..."
	if grep -q 'export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"' ~/.zshrc ~/.bashrc; then
		log "SSH_AUTH_SOCK is already exported in the shell startup file."
	else
		if [ -f ~/.zshrc ]; then
			if grep -q 'export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"' ~/.zshrc; then
				log "SSH_AUTH_SOCK is already exported in ~/.zshrc"
			else
				echo 'export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"' >>~/.zshrc
				log "Exported SSH_AUTH_SOCK to ~/.zshrc"
				source ~/.zshrc
			fi
		fi
		if [ -f ~/.bashrc ]; then
			if grep -q 'export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"' ~/.bashrc; then
				log "SSH_AUTH_SOCK is already exported in ~/.bashrc"
			else
				echo 'export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"' >>~/.bashrc
				log "Exported SSH_AUTH_SOCK to ~/.bashrc"
				source ~/.bashrc
			fi
		fi
		if [ ! -f ~/.zshrc ] && [ ! -f ~/.bashrc ]; then
			log "Unknown shell type. Please set the SSH_AUTH_SOCK environment variable manually in your shell startup file."
		fi
	fi

	cat <<EOF >~/.config/systemd/user/ssh-agent.service
[Unit]
Description=SSH authentication agent
[Service]
ExecStart=/usr/bin/ssh-agent -a %t/ssh-agent.socket -D
Type=simple
[Install]
WantedBy=default.target
EOF

	systemctl --user daemon-reload
	systemctl --user enable --now ssh-agent
else
	log "Skipping SSH Agent service setup."
fi

cat <<EOF
Installation complete!
EOF
