#!/usr/bin/env python3
"""Generate an ssh config file from the Ansible inventory.

Replacement for AISTool: templates host vars with Jinja (so e.g.
ansible_host: "{{ container_internal_ip }}" resolves) and emits ProxyJump
derived from ansible_ssh_common_args. When a jump target IP matches another
inventory host, the inventory alias is used so its Host block (identity,
user) applies to the hop as well.

The output file is rewritten from scratch on every run (with optional
timestamped backup), it is not merged with previous content.
"""

import re
import sys
from argparse import ArgumentParser, RawTextHelpFormatter
from datetime import datetime
from pathlib import Path
from shutil import copyfile

from ansible.errors import AnsibleError
from ansible.inventory.manager import InventoryManager
from ansible.parsing.dataloader import DataLoader
from ansible.template import Templar
from ansible.vars.manager import VariableManager

BACKUP_EXTENSION_FORMAT = "%Y%m%d_%H%M%S"
PROXYJUMP_RE = re.compile(r"-o\s+ProxyJump=(\S+)")


def get_args():
    parser = ArgumentParser(formatter_class=RawTextHelpFormatter, description=__doc__)
    parser.add_argument("inventory_file", help="ansible inventory file")
    parser.add_argument("-o", "--output", default="~/.ssh/config", type=Path,
                        help="ssh config output path (default: ~/.ssh/config)")
    parser.add_argument("-g", "--group", default="all", help="ansible inventory group to use")
    parser.add_argument("-u", "--user", default=None, help="overwrite ansible_user")
    parser.add_argument("-i", "--identityfile", default=None, type=Path,
                        help="identity file to set for all hosts")
    parser.add_argument("-d", "--dry-run", action="store_true",
                        help="print the generated config instead of writing it")
    parser.add_argument("--backup", action="store_true", default=True,
                        help="backup the output file before overwriting (default)")
    parser.add_argument("--no-backup", dest="backup", action="store_false")
    parser.add_argument("--forwardagent", action="store_true", default=True,
                        help="set ForwardAgent yes (default)")
    parser.add_argument("--no-forwardagent", dest="forwardagent", action="store_false")
    return parser.parse_args()


def collect_hosts(inventory_file, group, user, identity, forwardagent):
    loader = DataLoader()
    inventory = InventoryManager(loader=loader, sources=[str(inventory_file)])
    variables = VariableManager(loader=loader, inventory=inventory)

    entries = {}
    for host in inventory.get_hosts(group):
        host_vars = variables.get_vars(host=host)
        templar = Templar(loader=loader, variables=host_vars)
        name = host.get_name()

        # Network gear (RouterOS etc.) is not plain ssh, skip it.
        connection = host_vars.get("ansible_connection", "ssh")
        if connection not in ("ssh", "smart", "paramiko"):
            print(f"Skipping [{name}]: ansible_connection={connection}", file=sys.stderr)
            continue

        try:
            hostname = templar.template(
                host_vars.get("ansible_host", host_vars.get("ansible_ssh_host", name))
            )
        except AnsibleError as err:
            print(f"Skipping [{name}]: cannot resolve ansible_host ({err})", file=sys.stderr)
            continue

        entry = {"HostName": hostname}

        port = host_vars.get("ansible_port", host_vars.get("ansible_ssh_port"))
        if port:
            entry["Port"] = templar.template(port)

        entry["User"] = user or host_vars.get("ansible_user", host_vars.get("ansible_ssh_user", "root"))

        if identity and identity.exists():
            entry["IdentityFile"] = str(identity)
        elif host_vars.get("ansible_private_key_file"):
            entry["IdentityFile"] = templar.template(host_vars["ansible_private_key_file"])

        common_args = host_vars.get("ansible_ssh_common_args", "")
        if common_args:
            match = PROXYJUMP_RE.search(templar.template(common_args))
            if match:
                entry["ProxyJump"] = match.group(1)

        entry["ForwardAgent"] = "yes" if forwardagent else "no"
        entries[name] = entry

    # Prefer inventory aliases in ProxyJump so the jump hop inherits the
    # generated Host block (identity file, user) of e.g. bkk06/07/08.
    ip_to_alias = {e["HostName"]: alias for alias, e in entries.items() if "ProxyJump" not in e}
    for entry in entries.values():
        jump = entry.get("ProxyJump")
        if not jump:
            continue
        target = jump.split("@", 1)[-1]
        if target in ip_to_alias:
            entry["ProxyJump"] = ip_to_alias[target]

    return entries


def render(entries):
    lines = [f"# Generated by scripts/sshconfig.py on {datetime.now():%Y-%m-%d %H:%M:%S}",
             "# Do not edit manually, re-run: inv sshconfig", ""]
    for name in sorted(entries):
        lines.append(f"Host {name}")
        for key, value in entries[name].items():
            lines.append(f"    {key} {value}")
        lines.append("")
    return "\n".join(lines)


def main():
    args = get_args()
    output = args.output.expanduser()
    print(f"Inventory: {args.inventory_file}")
    print(f"Target: {output}")

    entries = collect_hosts(args.inventory_file, args.group, args.user,
                            args.identityfile, args.forwardagent)
    content = render(entries)

    if args.dry_run:
        print(content)
        return

    if args.backup and output.exists():
        copyfile(output, f"{output}.{datetime.now().strftime(BACKUP_EXTENSION_FORMAT)}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content)
    print(f"Wrote {len(entries)} host entries.")


if __name__ == "__main__":
    main()
