# Standards: 0.2
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: True

- name: Restart FDC XRP verifier
  ansible.builtin.systemd:
    name: fdc-xrp-verifier
    state: restarted
