---
ansible_host: "{{ container_internal_ip }}"
ansible_ssh_common_args: "-o ProxyJump=root@160.22.181.8"
container_internal_ip: "10.8.78.178"
host_name: "build-node-08"
host_timezone: "Asia/Bangkok"
netif:
  net0: "name=eth0,gw=10.8.0.1,ip={{ container_internal_ip }}/16,bridge={{ default_host_internal_bridge }}"

pinned_service: False
zabbix_ext_port: 10178
