---
ansible_host: "{{ container_internal_ip }}"
ansible_ssh_common_args: "-o ProxyJump=root@160.22.181.6"
container_internal_ip: "10.6.77.81"
host_name: "penumbra-01.ct.rotko.net"
host_timezone: "Asia/Bangkok"
netif:
  net0: "name=eth0,gw=10.6.0.1,ip={{ container_internal_ip }}/16,bridge={{ default_host_internal_bridge }}"
role: "penumbra"
pinned_service: True

default_network: "penumbra"
default_node_type: "penumbra"
#need to be uniqued
default_cometbft_p2p_port: 26681

default_penumbra_metric_port: 9600
default_cometbft_rpc_port: 26657
default_acbi_port: 26658
default_grpc_port: 8080
default_cometbft_database: "goleveldb"
default_domain: "antumbra.net"
# default_p2p_port: 33691
# default_p2p_port_ws: 34691
# default_p2p_port_wss: 35691
# default_rpc_port: 9691
# default_secure_rpc_port: 42691
# default_prom_port: 7691
# zabbix_ext_port: 10691
