---
ansible_host: "{{ container_internal_ip }}"
ansible_ssh_common_args: "-o ProxyJump=root@160.22.181.6"
container_ip: "192.168.121.10"
container_internal_ip: "10.6.121.10"
container_public_ip: "160.22.181.120"
container_public_ip6: "2401:a860:1120::11"
host_name: "rpc-kusama-01.ct.rotko.net"
host_timezone: "Asia/Bangkok"
netif:
  net0: "name=eth0,gw=10.6.0.1,ip=10.6.121.10/16,bridge={{ default_host_internal_bridge }}"
  net1: "name=eth1,ip={{ hostvars['rpc-kusama-01']['container_public_ip'] }}/32,ip6={{ hostvars['rpc-kusama-01']['container_public_ip6'] }}/128,bridge={{ default_host_public_bridge }}"
role: "polkadot"
pinned_service: True

default_telemetry_name: "Rotko Networks - {{ host_name.split('.')[0] }}"
default_domain: "{{ host_name }}"
default_domain_lb: "kusama.rotko.net"
default_domain_ibp: "rpc.ibp.network"
default_domain_dotters: "rpc.dotters.network"
default_ibp_repository: "git@github.com:GATOTECH-LTD/ibp-ssl"
default_dotters_repository: "git@github.com:senseless/dotters-ssl"
default_network: "kusama"
default_node_type: "endpoint"
default_pruning: "archive"
default_database: "rocksdb"
default_syncmode: "full"

default_p2p_port: 32001
default_p2p_port_ws: 30334
default_p2p_port_wss: 30335

default_bootnode_domain: "{{ default_network }}.boot.rotko.net"
default_bootnode_p2p_port: 32001
default_bootnode_p2p_port_ws: 30334
default_bootnode_p2p_port_wss: 30335

transition_bootnode_domain: "ksm14.rotko.net"
transition_bootnode_p2p_port: 33224
transition_bootnode_p2p_port_ws: 34224
transition_bootnode_p2p_port_wss: 35224

default_rpc_port: 9300
default_prom_port: 7300

default_secure_rpc_port: 42321
zabbix_ext_port: 10321
