---
ansible_host: "{{ container_internal_ip }}"
ansible_ssh_common_args: "-o ProxyJump=root@160.22.181.7"
container_ip: "192.168.77.42"
container_internal_ip: "10.7.142.10"
container_public_ip: "160.22.181.146"
container_public_ip6: "2401:a860:1146::11"
host_name: "rpc-paseo-02.rotko.net"
host_timezone: "Asia/Bangkok"
netif:
  net0: "name=eth0,gw=10.7.0.1,ip=10.7.142.10/16,bridge={{ default_host_internal_bridge }}"
  net1: "name=eth1,ip={{ hostvars['rpc-paseo-02']['container_public_ip'] }}/32,ip6={{ hostvars['rpc-paseo-02']['container_public_ip6'] }}/128,bridge={{ default_host_public_bridge }}"
role: "polkadot"
pinned_service: True

default_telemetry_name: "Rotko Networks - {{ host_name.split('.')[0] }} {{ default_node_type | capitalize }}"
default_domain: "{{ host_name }}"
default_domain_lb: "paseo.rotko.net"
default_domain_ibp: "rpc.ibp.network"
default_domain_dotters: "rpc.dotters.network"
default_ibp_repository: "git@github.com:GATOTECH-LTD/ibp-ssl"
default_dotters_repository: "git@github.com:senseless/dotters-ssl"
default_network: "paseo"
default_node_type: "endpoint"
default_pruning: "archive"
default_database: "rocksdb"
default_syncmode: "full"
default_p2p_port: 33342
default_p2p_port_ws: 34342
default_p2p_port_wss: 35342
default_rpc_port: 9342
default_secure_rpc_port: 42342
default_prom_port: 7342
zabbix_ext_port: 10342

default_bootnode_domain: "{{ host_name }}"
default_bootnode_p2p_port: 33342
default_bootnode_p2p_port_ws: 34342
default_bootnode_p2p_port_wss: 35342

transition_bootnode_domain: "pso16.rotko.net"
transition_bootnode_p2p_port: "{{ default_p2p_port + 10500 }}"
transition_bootnode_p2p_port_ws: "{{ default_p2p_port_ws + 10500 }}"
transition_bootnode_p2p_port_wss: "{{ default_p2p_port_wss + 10500 }}"
