---
ansible_host: "{{ container_internal_ip }}"
ansible_ssh_common_args: "-o ProxyJump=root@160.22.181.8"
container_internal_ip: "10.8.242.10"
host_name: "val-paseo-02.ct.rotko.net"
host_timezone: "Asia/Bangkok"
netif:
  net0: "name=eth0,gw=10.8.0.1,ip={{ container_internal_ip }}/16,bridge={{ default_host_internal_bridge }}"
role: "polkadot"
pinned_service: True

default_telemetry_name: "rotko-net-pso04"
default_chains_name: "paseo"
default_network: "paseo"
default_chain_spec: "{{ default_base_path }}/paseo.raw.json"
default_chain_spec_dl_url: "https://paseo-r2.zondax.ch/chain-specs/paseo.raw.json"
default_node_type: "validator"
default_pruning: 1000
default_database: paritydb
default_syncmode: warp

default_p2p_port: 34005
default_p2p_port_ws: 30334
default_p2p_port_wss: 30335

default_rpc_port: 9300
default_prom_port: 7300
default_secure_rpc_port: 42142
zabbix_ext_port: 10142
