# Standards: 0.2
---
- name: Ensure required lighthouse directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"
    mode: "0775"
    state: directory
  with_items:
    - "{{ ethereum_storage_path }}/lighthouse"
    - "{{ ethereum_base }}/lighthouse-v{{ ethereum_lighthouse_version }}"

- name: Render Lighthouse systemd unit file
  ansible.builtin.template:
    src: lighthouse.service.j2
    dest: "{{ ethereum_base }}/lighthouse.service"
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"
    mode: "0644"
  register: lighthouse_unit

- name: Symlink Lighthouse service to systemd
  ansible.builtin.file:
    src: "{{ ethereum_base }}/lighthouse.service"
    dest: /etc/systemd/system/lighthouse.service
    state: link
    force: True
    owner: root
    group: root
    mode: "0644"
  register: lighthouse_unit_link

- name: Systemd daemon-reload (lighthouse unit changed)
  ansible.builtin.systemd:
    daemon_reload: True
  when: lighthouse_unit.changed or lighthouse_unit_link.changed

- name: Download and extract lighthouse v{{ ethereum_lighthouse_version }}
  ansible.builtin.unarchive:
    src: "{{ ethereum_lighthouse_download_url }}"
    dest: "{{ ethereum_base }}/lighthouse-v{{ ethereum_lighthouse_version }}"
    remote_src: True
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"
    creates: "{{ ethereum_base }}/lighthouse-v{{ ethereum_lighthouse_version }}/lighthouse"
  when:
    - ansible_local['noderole']['node']['pinned'] != "True"
    - ansible_local['noderole']['lighthouse']['version'] != ethereum_lighthouse_version
  notify:
    - Add Lighthouse service version
    - Restart Lighthouse

- name: Symlink Lighthouse binary
  ansible.builtin.file:
    src: "{{ ethereum_base }}/lighthouse-v{{ ethereum_lighthouse_version }}/lighthouse"
    dest: "{{ ethereum_base }}/lighthouse"
    state: link
    force: True
    owner: "{{ ethereum_user }}"
    group: "{{ ethereum_user }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Lighthouse service is running
  ansible.builtin.systemd:
    name: lighthouse
    state: started
    enabled: True
