# Standards: 0.2
---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: True

- name: Restart FDC UTXO verifier
  ansible.builtin.systemd:
    name: "fdc-{{ fdc_utxo_chain }}-verifier"
    state: restarted
